[package]
name = "inip"
description = "A simple INI parser library"
version = "0.2.7"
repository = "https://github.com/HicaroD/INIp"
license = "MIT"
readme = "README.md"
edition = "2021"
keywords = ["parser", "ini"]
categories = ["parser-implementations", "parsing"]

[dependencies]
